groups:
  - name: my-alerts
    interval: 15s
    rules:
      - alert: NodeDown
        expr: up{job="node"} == 0
        for: 0m
        labels:
          team: infra
          env: prod
        annotations:
          message: "instance {{.Labels.instance}} is currently down"

      - alert: Dockerengine
        expr: up{job="db"} == 0
        for: 0m
        labels:
          team: Docker
          env: dev
        annotations:
          message: "{{.Labels.instance}} is currently down"

      - alert: Dockercontainer
        expr: up{job="Dockercontainer"} == 0
        for: 0m
        labels:
          team: Docker
          env: dev
        annotations:
          message: "instance {{.Labels.instance}} is currently down"